# Generated by Django 6.0.4 on 2026-04-17 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('personality_type', models.CharField(blank=True, choices=[('explorer', 'The Explorer'), ('romantic', 'The Romantic'), ('thinker', 'The Thinker'), ('thrill-seeker', 'The Thrill-Seeker'), ('empath', 'The Empath'), ('humorist', 'The Humorist')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('favorite_genre', models.CharField(blank=True, max_length=50)),
                ('taste_dna', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
