# Generated by Django 6.0.4 on 2026-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
